blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://www.banana.ch/en/feedback_documentation?url=https%3A%2F%2Fwww.banana.ch%2Fdoc%2Fen&topic=Documentation+Banana+Accounting%2B
    about: Help us improving the documentation by posting a feedback here.
